#!/usr/bin/php
<?php


    use pleaseHandler\AjaxHandler;
    use pleaseHandler\EmailHandler;
    use pleaseHandler\ExtraHandler;
    use pleaseHandler\FunctionsHandler;
    use pleaseHandler\HelperHandler;
    use pleaseHandler\HookHandler;
    use pleaseHandler\ModuleHandler;
    use pleaseHandler\RepoHandler;
    use pleaseHandler\RouteHandler;
    use pleaseHandler\TableViewHandler;
    use pleaseHandler\TraitHandler;

    class OWPactPlease{

        /**
         * OWPactPlease constructor.
         */

        private $handlersReferences;
        private $handlers;
        private $triggers;
        public function __construct()
        {
            $this->handlers = array();
            $this->triggers = array();
            $this->handlersReferences = array();
            $this->boot();
        }

        private function boot()
        {

            $this->RegisterModules();
            $this->RegisterHandler();

            $this->RenderDoc();

            $this->HandlerCLI();

        }

        private function RegisterModules()
        {
            $this->RegisterModule('base');
            $this->RegisterModule('pleaseHandler/CreateElement');
            $this->RegisterModule('pleaseHandler/HandlerTrait');
        }

        private function RegisterHandler()
        {

            $this->RegisterModule('pleaseHandler/PublishHandler','PublishHandler');

            $this->RegisterModule('pleaseHandler/HandlerPlease');

            $this->RegisterModule('pleaseHandler/AjaxHandler');
            $this->RegisterModule('pleaseHandler/EmailHandler');
            $this->RegisterModule('pleaseHandler/HookHandler');
            $this->RegisterModule('pleaseHandler/RepoHandler');
            $this->RegisterModule('pleaseHandler/HelperHandler');
            $this->RegisterModule('pleaseHandler/ExtraHandler');
            $this->RegisterModule('pleaseHandler/RouteHandler');
            $this->RegisterModule('pleaseHandler/TraitHandler');
            $this->RegisterModule('pleaseHandler/TableViewHandler');
            $this->RegisterModule('pleaseHandler/ModuleHandler');
            $this->RegisterModule('pleaseHandler/FunctionsHandler');

        }

        private function RegisterModule($module,$classReference=false)
        {
            require_once $module.'.php';
            if($classReference){
                $this->handlers[] = $classReference;
            }
        }

        private function HandlerCLI()
        {

            global $argv;

            if($argv){
                $current_cmd = $argv[1];

                if($current_cmd == 'make'){

                    $this->CheckIfAlreadyPublished();
                    if(isset($argv[2])){
                                $this->ProcessHandler($argv);
                                $this->PrintAvailableTriggers();
                    }else{
                        $this->PrintAvailableTriggers();
                    }
                }else{

                    // Check if is Publish Case
                    if($current_cmd == 'publish'){

                        $publish = new PublishHandler();
                        $publish->Publish();

                    }else{
                        echo ">>>>> please Enter valid command";
                        $this->PrintDoc();
                    }
                }

            }else{
                echo "Please enter valid command";
            }
        }


        /*
         * Process Handlers
         */
        private function ProcessHandler($argv)
        {

            new AjaxHandler($argv);
            new RepoHandler($argv);
            new EmailHandler($argv);
            new HelperHandler($argv);
            new HookHandler($argv);
            new ExtraHandler($argv);
            new RouteHandler($argv);
            new TraitHandler($argv);
            new TableViewHandler($argv);
            new ModuleHandler($argv);
            new FunctionsHandler($argv);


        }

        private function CheckIfAlreadyPublished()
        {
            $Registray_file = OWPactConfig::getOWPDir().'/RegisteryOwpact.php';

            if(!file_exists($Registray_file)){
                echo "Can't find the RegisteryOwpact.php in your project.".
                    "Do you published ? else please publish first 'php owp publish'";
                die();
            }
        }

        /*
         * Generate Docs for Help
         */
        private function RenderDoc()
        {
            $this->handlers = array(

                AjaxHandler::getDoc(),
                RepoHandler::getDoc(),
                EmailHandler::getDoc(),
                HelperHandler::getDoc(),
                HookHandler::getDoc(),
                ExtraHandler::getDoc(),
                RouteHandler::getDoc(),
                TraitHandler::getDoc(),
                TableViewHandler::getDoc(),
                ModuleHandler::getDoc(),
                FunctionsHandler::getDoc(),
            );


            foreach($this->handlers as $handler){
                $this->triggers = array($handler['trigger']);
            }
        }


        private  function PrintDoc()
        {
            if($this->handlers){
                echo "\n";
                echo Console::log('=================== OWPACT HELP ===============','green',false);
                echo "\n";
                foreach($this->handlers as $handler){
                    echo "\n";
                    echo Console::log($handler['trigger'],'cyan',false);
                    echo Console::log(" ||  ",'bold',false);
                    echo Console::log($handler['demo'].' : ','green',false);
                    Console::log($handler['doc'],'white',false,'brown');
                    echo "\n";
                }
                echo "\n";
                echo Console::log('=================== OWPACT HELP ===============','green',false);
            }
        }

        private function PrintAvailableTriggers()
        {

            $word = Console::white("Please enter a valid entry:\n", 'white', true, 'red');

            foreach($this->triggers as $trigger){
                $word .= Console::white($trigger,'white',true);
            }
            echo $word;

        }


    }

    new OWPactPlease();